"""Export file download API routes.

Provides endpoints for downloading exported files generated by the export_file node.
"""

import os
from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

router = APIRouter()

EXPORT_DIR = os.getenv("EXPORT_DIR", os.path.join(os.path.expandvars("%TEMP%"), "studysolo_exports"))


@router.get("/download/{filename}")
async def download_export(filename: str):
    """Download an exported file by filename.

    The filename is the UUID-suffixed filename generated by file_converter.
    """
    # Sanitize filename to prevent path traversal
    safe_filename = os.path.basename(filename)
    filepath = os.path.join(EXPORT_DIR, safe_filename)

    if not os.path.exists(filepath):
        raise HTTPException(status_code=404, detail="文件不存在或已过期")

    # Determine media type
    media_types = {
        ".pdf": "application/pdf",
        ".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        ".md": "text/markdown",
    }
    ext = os.path.splitext(safe_filename)[1].lower()
    media_type = media_types.get(ext, "application/octet-stream")

    return FileResponse(
        path=filepath,
        filename=safe_filename,
        media_type=media_type,
    )
