"""Export file download API routes.

Provides endpoints for downloading exported files generated by the export_file node.
Downloads require authentication to prevent unauthorized access to user files.
"""

import os
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse

from app.core.deps import get_current_user

router = APIRouter()

EXPORT_DIR = os.getenv("EXPORT_DIR", os.path.join(os.path.expandvars("%TEMP%"), "studysolo_exports"))


@router.get("/download/{filename}")
async def download_export(
    filename: str,
    current_user: dict = Depends(get_current_user),
):
    """Download an exported file by filename.

    The filename is the UUID-suffixed filename generated by file_converter.
    Requires authentication — only logged-in users can download files.
    """
    # Sanitize filename to prevent path traversal
    safe_filename = os.path.basename(filename)

    # Additional safety: reject filenames with suspicious patterns
    if ".." in safe_filename or "/" in safe_filename or "\\" in safe_filename:
        raise HTTPException(status_code=400, detail="非法文件名")

    filepath = os.path.join(EXPORT_DIR, safe_filename)

    if not os.path.exists(filepath):
        raise HTTPException(status_code=404, detail="文件不存在或已过期")

    # Verify the resolved path is still inside export dir (belt-and-suspenders)
    real_path = os.path.realpath(filepath)
    real_export = os.path.realpath(EXPORT_DIR)
    if not real_path.startswith(real_export):
        raise HTTPException(status_code=403, detail="访问被拒绝")

    # Determine media type
    media_types = {
        ".pdf": "application/pdf",
        ".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        ".md": "text/markdown",
    }
    ext = os.path.splitext(safe_filename)[1].lower()
    media_type = media_types.get(ext, "application/octet-stream")

    return FileResponse(
        path=filepath,
        filename=safe_filename,
        media_type=media_type,
    )
